### ISSUE TITLE
Omori crash when load backstage save file

### ISSUE THREAD

**Issue by tungdo0602** [fifomori/android#8]
![Screenshot_20240808_164739_OMORI](https://github.com/user-attachments/assets/d92d641e-e73a-4506-8bd0-197fbeb7dae8)

**Comment by tungdo0602** [comment]
In the backstage before good ending and bad ending

**Comment by tungdo0602** [comment]
[file6.txt](https://github.com/user-attachments/files/16541269/file6.txt)
Save file if you need (change .txt to .rpgsave because github doesn't allowed that file type)

**Comment by cafeed28** [comment]
should be fixed in [latest release](https://github.com/fifomori/android/releases/tag/v1.3.1-beta), but your save file is corrupted (constructor name is still incorrect Rectangle2), here is fixed version (rename to .rpgsave)
[file6_fixed.txt](https://github.com/user-attachments/files/16544810/file6_fixed.txt)

**Comment by tungdo0602** [comment]
> should be fixed in [latest release](https://github.com/fifomori/android/releases/tag/v1.3.1-beta), but your save file is corrupted (constructor name is still incorrect Rectangle2), here is fixed version (rename to .rpgsave) [file6_fixed.txt](https://github.com/user-attachments/files/16544810/file6_fixed.txt)

Umm thanks you for the fixes!
